### ISSUE TITLE
Automated symlinks

### ISSUE THREAD

**Issue by enriquecaballero** [enriquecaballero/dotfiles#1]
Create an install script that automates the symlink process

**Comment by joshgordon** [comment]
I use this method and am a huge fan of it: http://brandon.invergo.net/news/2012-05-26-using-gnu-stow-to-manage-your-dotfiles.html

Also would let you have like a bashrc-mac module and a bashrc-linux module for platform dependant stuff.

**Comment by enriquecaballero** [comment]
I'll take a look at that

**Comment by enriquecaballero** [comment]
Restructured the repository so that it can be managed using Stow
